config/routes.rb
Rails.application.routes.draw do
  resources :repositories do
    resources :issues
  end
  get 'pages/main'
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  get "home/index"

  # sign up page with form:
  get 'users/new' => 'users#new', as: :new_user

  # create (post) action for when sign up form is submitted:
  post 'users' => 'users#create'

  # log in page with form:
  get '/login'     => 'sessions#new'

  # create (post) action for when log in form is submitted:
  post '/login'    => 'sessions#create'

  # delete action to log out:
  delete '/logout' => 'sessions#destroy'

  get 'pages/secret', as: :secret

  get 'repositories/show' => 'repositories#show', as: :show_repo

  #get 'repositories', as: :show_repo

  #get 'repository/new' => 'repository#new', as: :new_repository

  resources :posts
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :repository
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @repository = Repository.find(params[:repository_id])
    @issue = @repository.issues.build
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @repository = Repository.find(params[:repository_id])
    @issue = @repository.issues.create(params[:issue]).permit(:subject, :text)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to show_repo_path(@repository), notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:subject, :text)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_with model: [@repository, @repository.issues.build], local: true do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issues</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.subject %></td>
        <td><%= issue.text %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Back', show_repo_path(@repository) %> |

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @issue.subject %>
</p>

<p>
  <strong>Text:</strong>
  <%= @issue.text %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>